sonar.projectKey=ThouaibatSelim_EC063
sonar.organization=thouaibatselim
sonar.sources=app
sonar.tests=tests
sonar.exclusions=**/vendor/**,**/node_modules/**,**/storage/**,**/bootstrap/cache/**
sonar.php.coverage.reportPaths=coverage.xml
