sonar.projectKey=skillhub-groupe_skillhub-backend
sonar.organization=skillhub-groupe
sonar.sources=app
sonar.tests=tests
sonar.exclusions=**/vendor/**,**/node_modules/**,**/storage/**,**/bootstrap/cache/**
sonar.php.coverage.reportPaths=coverage.xml
